import pytest

from src.head_hunter_api import HeadHunterAPI
from src.vacancy import Vacancy


@pytest.fixture
def hh_api() -> HeadHunterAPI:
    return HeadHunterAPI()


@pytest.fixture
def response_api() -> dict:
    return {
        "items": [
            {
                "id": "124016761",
                "premium": False,
                "name": "Middle Backend-разработчик (Python)",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
                "salary": None,
                "salary_range": None,
                "type": {"id": "open", "name": "Открытая"},
                "address": {
                    "city": "Ташкент",
                    "street": "Университетская улица",
                    "building": "5/1",
                    "lat": 41.35056621912094,
                    "lng": 69.20756772088437,
                    "description": None,
                    "raw": "Ташкент, Университетская улица, 5/1",
                    "metro": None,
                    "metro_stations": [],
                    "id": "17685771",
                },
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2025-08-13T14:56:03+0300",
                "created_at": "2025-08-13T14:56:03+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=124016761",
                "show_contacts": True,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/124016761?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/124016761",
                "relations": [],
                "employer": {
                    "id": "11577307",
                    "name": "SAMYY SOFT",
                    "url": "https://api.hh.ru/employers/11577307",
                    "alternate_url": "https://hh.ru/employer/11577307",
                    "logo_urls": None,
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11577307",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Опыт разработки с <highlighttext>Python</highlighttext> и FastAPI не менее 3 лет. "
                    "Уверенные знания SQLAlchemy, Alembic, Pydantic. Практический опыт с PostgreSQL, "
                    "Redis...",
                    "responsibility": "Разработка и тестирование масштабируемых RESTful API на FastAPI. Интеграция с "
                    "сервисами: PostgreSQL, Redis, RabbitMQ. Проектирование backend-систем на "
                    "основе микросервисной...",
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": False,
                "fly_in_fly_out_duration": [],
                "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
                "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
                "work_schedule_by_days": [{"id": "SIX_ON_ONE_OFF", "name": "6/1"}],
                "night_shifts": False,
                "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
                "accept_incomplete_resumes": False,
                "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "employment_form": {"id": "FULL", "name": "Полная"},
                "internship": False,
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "124008575",
                "premium": False,
                "name": "Backend-разработчик",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
                "salary": {"from": 40000, "to": 100000, "currency": "USD", "gross": True},
                "salary_range": {
                    "from": 400,
                    "to": 1000,
                    "currency": "USD",
                    "gross": True,
                    "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                    "frequency": {"id": "MONTHLY", "name": "Раз в\xa0месяц"},
                },
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2025-08-13T12:52:13+0300",
                "created_at": "2025-08-13T12:52:13+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=124008575",
                "show_contacts": True,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/124008575?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/124008575",
                "relations": [],
                "employer": {
                    "id": "11842692",
                    "name": "SECTOR SOFT",
                    "url": "https://api.hh.ru/employers/11842692",
                    "alternate_url": "https://hh.ru/employer/11842692",
                    "logo_urls": None,
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11842692",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "PostgreSQL kabi ma’lumotlar bazalari bilan ishlash ko'nikmasi. - Backend "
                    "tizimlarini optimallashtirish va shkalalash bo'yicha tajriba. - Telegram botlar "
                    "yaratish...",
                    "responsibility": "Backend dasturchi qidirilmoqda! (<highlighttext>python</highlighttext>). - "
                    "Docker va konteynerlashgan muhitda ishlash ko'nikmasi. - Yuqori darajadagi "
                    "backend tizimlarni loyihalash va amalga oshirish. - ",
                },
                "contacts": None,
                "schedule": {"id": "fullDay", "name": "Полный день"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [],
                "accept_temporary": True,
                "fly_in_fly_out_duration": [],
                "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
                "working_hours": [{"id": "HOURS_9", "name": "9 часов"}],
                "work_schedule_by_days": [{"id": "SIX_ON_ONE_OFF", "name": "6/1"}],
                "night_shifts": False,
                "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
                "accept_incomplete_resumes": False,
                "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "employment_form": {"id": "FULL", "name": "Полная"},
                "internship": False,
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
        ],
        "found": 9292,
        "pages": 1000,
        "page": 0,
        "per_page": 2,
        "clusters": None,
        "arguments": None,
        "fixes": None,
        "suggests": None,
        "alternate_url": "https://hh.ru/search/vacancy?enable_snippets=true&items_on_page=2&text=Python",
    }


@pytest.fixture
def list_vacancies() -> list:
    return [
        {
            "id": "124016761",
            "premium": False,
            "name": "Middle Backend-разработчик (Python)",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Ташкент",
                "street": "Университетская улица",
                "building": "5/1",
                "lat": 41.35056621912094,
                "lng": 69.20756772088437,
                "description": None,
                "raw": "Ташкент, Университетская улица, 5/1",
                "metro": None,
                "metro_stations": [],
                "id": "17685771",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-08-13T14:56:03+0300",
            "created_at": "2025-08-13T14:56:03+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=124016761",
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/124016761?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/124016761",
            "relations": [],
            "employer": {
                "id": "11577307",
                "name": "SAMYY SOFT",
                "url": "https://api.hh.ru/employers/11577307",
                "alternate_url": "https://hh.ru/employer/11577307",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11577307",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Опыт разработки с <highlighttext>Python</highlighttext> и FastAPI не менее 3 лет. "
                "Уверенные знания SQLAlchemy, Alembic, Pydantic. Практический опыт с PostgreSQL, "
                "Redis...",
                "responsibility": "Разработка и тестирование масштабируемых RESTful API на FastAPI. Интеграция с "
                "сервисами: PostgreSQL, Redis, RabbitMQ. Проектирование backend-систем на основе "
                "микросервисной...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "SIX_ON_ONE_OFF", "name": "6/1"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "124008575",
            "premium": False,
            "name": "Backend-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": {"from": 40000, "to": 100000, "currency": "USD", "gross": True},
            "salary_range": {
                "from": 400,
                "to": 1000,
                "currency": "USD",
                "gross": True,
                "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                "frequency": {"id": "MONTHLY", "name": "Раз в\xa0месяц"},
            },
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-08-13T12:52:13+0300",
            "created_at": "2025-08-13T12:52:13+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=124008575",
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/124008575?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/124008575",
            "relations": [],
            "employer": {
                "id": "11842692",
                "name": "SECTOR SOFT",
                "url": "https://api.hh.ru/employers/11842692",
                "alternate_url": "https://hh.ru/employer/11842692",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=11842692",
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "PostgreSQL kabi ma’lumotlar bazalari bilan ishlash ko'nikmasi. - Backend tizimlarini "
                "optimallashtirish va shkalalash bo'yicha tajriba. - Telegram botlar yaratish...",
                "responsibility": "Backend dasturchi qidirilmoqda! (<highlighttext>python</highlighttext>). - Docker "
                "va konteynerlashgan muhitda ishlash ko'nikmasi. - Yuqori darajadagi backend "
                "tizimlarni loyihalash va amalga oshirish. - ",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": True,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_9", "name": "9 часов"}],
            "work_schedule_by_days": [{"id": "SIX_ON_ONE_OFF", "name": "6/1"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
    ]


@pytest.fixture
def vacancy_1() -> Vacancy:
    return Vacancy("Python Developer", "https://hh.ru/vacancy/123456", 100000, "3 года")


@pytest.fixture
def vacancy_2() -> Vacancy:
    return Vacancy("Java Developer", "https://hh.ru/vacancy/654321", 90000, "2 года")
